---
version: '3'

services:
  app:
    # https://github.com/linuxserver/docker-nextcloud/releases
    image: lscr.io/linuxserver/nextcloud:${NEXTCLOUD_VERSION:-latest}
    container_name: nextcloud_app
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${NEXTCLOUD_PATH}/config:/config
      - ${NEXTCLOUD_PATH}/data:/data
    ports:
      - 3443:443
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: "service_started"
      redis:
        condition: "service_started"
    
  mariadb:
    # https://github.com/linuxserver/docker-mariadb/releases
    image: lscr.io/linuxserver/mariadb:${MARIADB_VERSION:-latest}
    container_name: nextcloud_mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${NEXTCLOUD_MARIADB_PASSWORD}
    volumes:
      - ${NEXTCLOUD_PATH}/mariadb:/config
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  redis:
    # https://hub.docker.com/_/redis?tab=tags
    image: redis:${REDIS_VERSION:-latest}
    container_name: nextcloud_redis
    # volumes:
    #   - ${NEXTCLOUD_PATH}/redis:/data
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped