###############################################################################
# WHOAMI  
# Docker image that returns information about the client 
---
version: '3.8'

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - traefik_proxy
    ports:
      - "8081:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Pathprefix(`/whoami`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true
