---
version: "3"

networks:
  # Cloudflare zero trust tunnel network
  tunnel_network:
    external: true


services:
  fava:
    # https://hub.docker.com/r/yegle/fava
    # https://github.com/yegle/fava-docker
    image: yegle/fava:${FAVA_VERSION:-latest}
    container_name: fava_app
    volumes:
      - ${BEANCOUNT_PATH}:/bean
    environment:
      - BEANCOUNT_FILE=${BEANCOUNT_FILE}
    # entrypoint: 
    #   - fava
    #   - ${BEANCOUNT_FILE}
    # ports:
    #   - 11155:5000
    networks:
      - tunnel_network
    user: "${PUID}:${PGID}"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"