version: '3.7'
## https://github.com/yyoshiki41/docker-compose-redash

services:
  server:
    image: redash/redash:${REDASH_VERSION:-10.0.0.b50363}
    container_name: redash_server
    depends_on:
      - postgres
      - redis
    ports:
      - "11500:5000"
      - "11578:5678"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres:password@postgres/postgres"
      REDASH_RATELIMIT_ENABLED: "false"
      REDASH_ENFORCE_CSRF: "true"
  
  worker:
    image: redash/redash:${REDASH_VERSION:-10.0.0.b50363}
    container_name: redash_worker
    command: worker
    depends_on:
      - server
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres:password@postgres/postgres"
  
  scheduler:
    image: redash/redash:${REDASH_VERSION:-10.0.0.b50363}
    container_name: redash_scheduler
    command: scheduler
    depends_on:
      - server
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres:password@postgres/postgres"
  
  redis:
    image: redis:${REDIS_VERSION:-7.0-rc3-alpine}
    container_name: redash_redis
    restart: unless-stopped

  postgres:
    image: postgres:${POSTGRES_VERSION:-14.2-alpine}
    container_name: redash_postgres
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "password"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${REDASH_PATH}:/var/lib/postgresql/data