###############################################################################
# SWAGGER (OPENAPI)
#
# Simplify API development for users, teams, and enterprises with the Swagger 
# open source and professional toolset. Find out how Swagger can help you design
# and document your APIs at scale.
---
version: "3.8"
services:
  # https://github.com/swagger-api/swagger-editor
  swagger-editor:
    image: swaggerapi/swagger-editor:${SWAGGER_EDITOR_VERSION:-latest}
    container_name: "swagger_editor"
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ${SWAGGER_FILE:-./openapi.yaml}:/swagger.yaml
    environment:
      - "SWAGGER_FILE: /swagger.yaml"

  # https://github.com/swagger-api/swagger-ui
  swagger-ui:
    image: swaggerapi/swagger-ui:${SWAGGER_UI_VERSION:-latest}
    container_name: "swagger_ui"
    restart: unless-stopped
    ports:
      - "8082:8080"
    volumes:
      - ${SWAGGER_FILE:-./openapi.yaml}:/swagger.yaml
    environment:
      SWAGGER_JSON: /swagger.yaml