###############################################################################
# AUDIOBOOKSHELF
# https://www.audiobookshelf.org/
---
version: "3.8"

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:${AUDIOBOOKSHELF_VERSION:-latest}
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "${AUDIOBOOKSHELF_PORT:-13378}:80"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "${AUDIOBOOKS_PATH:-/media/audiobooks}:/audiobooks"
      - "${PODCASTS_PATH:-/media/podcasts}:/podcasts"
      - "${AUDIOBOOKSHELF_PATH:-~/Docker/audiobookshelf}/config:/config"
      - "${AUDIOBOOKSHELF_PATH:-~/Docker/audiobookshelf}/metadata:/metadata"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockge.rule=Pathprefix(`/dockge`)"
      - "traefik.http.services.dockge.loadbalancer.server.port=5001"
      - "com.centurylinklabs.watchtower.enable=true"