###############################################################################
# HEIMDALL 
# Dashboard application
---
version: '3.8'

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:${HEIMDALL_VERSION:-latest}
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - ${HEIMDALL_PATH:-~/Docker/heimdall}/config:/config
    ports:
      # - "11443:443" # https port
      - "8089:80" # http port
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.entrypoints=http"
      - "traefik.http.routers.heimdall.rule=Pathprefix(`/dashboard`)"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"

networks:
  default:
    name: traefik_proxy
    external: true
