###############################################################################
# HEIMDALL 
# Dashboard application
---
version: '3.8'

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:${HEIMDALL_VERSION:-latest}
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - ${HEIMDALL_PATH:-~/Docker/heimdall}/config:/config
    ports:
      - "11443:443"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Pathprefix(`/dashboard`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"

networks:
  default:
    name: traefik_proxy
    external: true
