# Prometheus Monitoring

networks:
  default:
    name: prometheus
    driver: bridge
  traefik:
    external: true

services:
  prometheus:
    # https://hub.docker.com/r/prom/prometheus/tags
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    container_name: prometheus
    # user: "${PUID}"
    networks:
      - default
      - traefik
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/prometheus.yml
      - ${PROMETHEUS_PATH}:/etc/prometheus
      - ${PROMETHEUS_PATH}/data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.external-url=/${PROMETHEUS_URL_PATH}/" # Domain path is messing up metrics config
    labels:
      ## Watch for container image updates
      - "com.centurylinklabs.watchtower.enable=true"

      ## Configure Treafik proxy
      ## https://blog.cubieserver.de/2020/configure-prometheus-on-a-sub-path-behind-reverse-proxy/
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`${PROMETHEUS_HOSTNAME}`) && PathPrefix(`/${PROMETHEUS_URL_PATH}/`)"
      - "traefik.http.routers.prometheus.entrypoints=https"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.docker.network=traefik"