networks:
  default: # Give the default network a name, to use in other containers
    name: ntfy
    driver: bridge
  cloudflare:
    external: true

services:
  ntfy:
    # https://hub.docker.com/r/binwiederhier/ntfy
    image: binwiederhier/ntfy:${NTFY_VERSION:-latest}
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=${NTFY_TZ:-UTC}
      - NTFY_BASE_URL=${NTFY_DOMAIN:?FQDN is required}
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_BEHIND_PROXY=true
      - NTFY_ATTACHMENT_CACHE_DIR=/var/cache/ntfy/attachments
      - NTFY_UPSTREAM_BASE_URL=https://ntfy.sh # Optional if you need push notifications on iOS
      - NTFY_AUTH_FILE=/etc/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_ENABLE_LOGIN=true
    # user: UID:GID # optional: replace with your own user/group or uid/gid
    volumes:
      - ${NTFY_PATH:-.}/cache:/var/cache/ntfy
      - ${NTFY_PATH:-.}/config:/etc/ntfy
    networks:
      - default
      - cloudflare
    ports:
      - ${NTFY_PORT:-8091}:80
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"