---
# Ntfy Notification Server Stack
# -----------------------------
#
# Required Environment Variables:
# - NTFY_HOSTNAME: FQDN for the server
# - NTFY_VERSION: Container version (optional, defaults to 'latest')
# - NTFY_TZ: Timezone (optional, defaults to UTC)
# - NTFY_PATH: Data directory path (optional, defaults to './') 
# - NTFY_PORT: Host port (optional, defaults to 8091)
#
# Usage:
# 1. Create a .env file with required variables
# 2. Start the stack: docker compose up -d
# 3. Access the server at http://<your-server-ip>:<NTFY_PORT>
# 4. For HTTPS, set up a Cloudflare Tunnel or use a reverse proxy
# 5. To connect other containers to this ntfy server:
#    networks:
#      cloudflare:
#        external: true

networks:
  cloudflare:
    external: true

services:
  ntfy:
    # https://hub.docker.com/r/binwiederhier/ntfy
    image: binwiederhier/ntfy:${NTFY_VERSION:-latest}
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=${NTFY_TZ:-UTC}
      - NTFY_BASE_URL=https://${NTFY_HOSTNAME:?FQDN is required}
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_BEHIND_PROXY=true
      - NTFY_ATTACHMENT_CACHE_DIR=/var/cache/ntfy/attachments
      - NTFY_UPSTREAM_BASE_URL=https://ntfy.sh # Optional if you need push notifications on iOS
      - NTFY_AUTH_FILE=/etc/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_ENABLE_LOGIN=true
    # user: UID:GID # optional: replace with your own user/group or uid/gid
    volumes:
      - ${NTFY_PATH:-.}/cache:/var/cache/ntfy
      - ${NTFY_PATH:-.}/config:/etc/ntfy
    ports:
      - ${NTFY_PORT:-8091}:80
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
    # Add memory and CPU limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    labels:
      ## Keep container image updated to latest version
      - "com.centurylinklabs.watchtower.enable=true"
    networks: 
      - cloudflare