
services:
  internet_monitor:
    # https://github.com/beykansen/internet-speed-monitor
    image: ghcr.io/beykansen/internet-speed-monitor:${INTERNET_SPEED_MONITOR_VERSION:-latest}
    container_name: monitoring_speedtest
    environment:
      - PORT=8083
      - INTERVAL=15 # In minutes
      - CALLBACK=${SPEEDTEST_CALLBACK}
    ports:
      - "8083:8083"
    networks:
      - default
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"