###############################################################################
# TRAEFIX 
# Reverse proxy
---
version: '3.8'

services:
  traefik:
    image: "traefik:${TRAEFIX_VERSION:-latest}"
    container_name: "traefik"
    restart: unless-stopped
    command:
      ## Log Configuration
      # - "--accesslog=true"
      # - "--log.level=DEBUG"
      ## Don't force https
      - "--api.insecure=true"
      - "--api.dashboard=false" # Disable dashboard
      ## Entry Points 
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      ## Docker Config
      - "--providers.docker=true"
      # - "--providers.docker.exposedbydefault=false"
      # - "--providers.docker.network=traefik_proxy"
      ## Misc Configuration
      - '--global.sendanonymoususage=false'
    ## [source]:[destination] 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ## [host]:[container]
    ports:
      - "80:80" # http entry point port
      - "443:443" # https entry point port
      # - "8088:8080" # Web GUI (dashboard) port
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    name: traefik_proxy
    driver: bridge
