version: "3.3"
# https://github.com/plausible/hosting

networks:
  default: # this docker-compose network
    name: plausible_network
    driver: bridge
  cloudflared_tunnel_network: # Cloudflare zero trust tunnel network
    external: true

services:
  mail:
    image: bytemark/smtp
    container_name: plausible_smtp
    restart: unless-stopped

  plausible_db:
    # https://hub.docker.com/_/postgres/
    # supported versions are 12, 13, and 14
    image: postgres:${PLAUSIBLE_POSTGRES_VERSION:-14-alpine} 
    container_name: plausible_postgres
    restart: unless-stopped
    volumes:
      - ${PLAUSIBLE_PATH}/postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    # https://hub.docker.com/r/clickhouse/clickhouse-server
    image: clickhouse/clickhouse-server:${PLAUSIBLE_CLICKHOUST_VERSION:-22.6-alpine}
    container_name: plausible_clickhouse
    restart: unless-stopped
    volumes:
      - ${PLAUSIBLE_PATH}/clickhouse:/var/lib/clickhouse
      - ${PLAUSIBLE_PATH}/log:/var/log/clickhouse-server
      - ${PLAUSIBLE_PATH}:/etc/clickhouse-server/config.d/logging.xml:ro
      - ${PLAUSIBLE_PATH}:/etc/clickhouse-server/users.d/logging.xml:ro
      - /etc/localtime:/etc/localtime:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  geoip:
    # https://hub.docker.com/r/maxmindinc/geoipupdate
    image: maxmindinc/geoipupdate:${PLAUSIBLE_GEOIPUPDATE_VERSION:-v5}
    container_name: plausible_geoipupdate
    restart: unless-stopped
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168 ## update every 7 days
      - GEOIPUPDATE_ACCOUNT_ID=${PLAUSIBLE_GEOIPUPDATE_ACCOUNT_ID} ## https://www.maxmind.com/en/home
      - GEOIPUPDATE_LICENSE_KEY=${PLAUSIBLE_GEOIPUPDATE_LICENSE_KEY} ## https://www.maxmind.com/en/accounts/756446/license-key/create
    volumes:
      - ${PLAUSIBLE_PATH}/geoip:/usr/share/GeoIP

  plausible:
    # https://hub.docker.com/r/plausible/analytics
    image: plausible/analytics:${PLAUSIBLE_ANALYTICS_VERSION:-v1.5}
    container_name: plausible_app
    restart: unless-stopped
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
      - geoip
    ports:
      - 8000:8000
    networks:
      - default
      - cloudflared_tunnel_network
    environment:
      - BASE_URL=${PLAUSIBLE_BASE_URL}
      - SECRET_KEY_BASE=${PLAUSIBLE_SECRET_KEY_BASE} # openssl rand -base64 64 | tr -d '\n' ; echo
      - DISABLE_REGISTRATION=true
      - MAILER_EMAIL=${PLAUSIBLE_MAILER_EMAIL}
      - SMTP_HOST_ADDR=smtp.gmail.com
      - SMTP_HOST_PORT=587
      - SMTP_USER_NAME=${PLAUSIBLE_SMTP_USER_NAME}
      - SMTP_USER_PWD=${PLAUSIBLE_SMTP_USER_PWD}
      - SMTP_HOST_SSL_ENABLED=true
      - SMTP_RETRIES=20
      - CRON_ENABLED=true