---
version: '3'

networks:
  tunnel_network:
    driver: bridge

services:
  cloudflared:
    # https://github.com/cloudflare/cloudflared/releases
    image: cloudflare/cloudflared:${CLOUDFLARED_VERSION:-latest}
    container_name: cloudflared_tunnel
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - tunnel_network # Other contianers to connect to the tunnel through cloudflared_tunnel_network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"