networks:
  default: # this docker-compose network
    name: nextcloud
    driver: bridge
  cloudflare: # Cloudflare zero trust tunnel network
    external: true

services:
  nextcloud:
    # https://github.com/linuxserver/docker-nextcloud/releases
    image: lscr.io/linuxserver/nextcloud:${NEXTCLOUD_VERSION:-latest}
    container_name: nextcloud_app
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${NEXTCLOUD_PATH}/config:/config
      - ${NEXTCLOUD_PATH}/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3443:443/tcp # Can be commented out once cloudflare up
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
    networks:
      - default
      - cloudflare
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    
  mariadb:
    # https://github.com/linuxserver/docker-mariadb/releases
    image: lscr.io/linuxserver/mariadb:${MARIADB_VERSION:-latest}
    container_name: nextcloud_mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${NEXTCLOUD_MARIADB_PASSWORD}
    volumes:
      - ${NEXTCLOUD_PATH}/mariadb:/config
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # networks:
    #   - default
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  redis:
    # https://hub.docker.com/_/redis?tab=tags
    image: redis:${REDIS_VERSION:-latest}
    container_name: nextcloud_redis
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # networks:
    #   - default
    labels:
      - "com.centurylinklabs.watchtower.enable=true"