###############################################################################
# WATCH TOWER
# With watchtower you can update the running version of your containerized app simply by pushing a new image to the Docker Hub or your own image registry.
#
# https://github.com/containrrr/watchtower

services:
  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_VERSION:-latest}
    container_name: watchtower
    environment:
      # https://containrrr.dev/watchtower/arguments/#cleanup
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP:-false}
      # https://containrrr.dev/watchtower/arguments/#filter_by_enable_label
      - WATCHTOWER_LABEL_ENABLE=${WATCHTOWER_LABEL_ENABLE:-false}
      # https://containrrr.dev/watchtower/arguments/#scheduling
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE:-0 0 0 * * *} ## https://pkg.go.dev/github.com/robfig/cron@v1.2.0#hdr-CRON_Expression_Format
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
