###############################################################################
# WATCH TOWER
# With watchtower you can update the running version of your containerized app simply by pushing a new image to the Docker Hub or your own image registry.
#
# https://github.com/containrrr/watchtower

# networks:
#   ntfy:
#     external: true

services:
  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_VERSION:-latest}
    container_name: watchtower
    # networks:
    #   - ntfy
    environment:
      # https://containrrr.dev/watchtower/arguments/#cleanup
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP:-false}
      # https://containrrr.dev/watchtower/arguments/#filter_by_enable_label
      - WATCHTOWER_LABEL_ENABLE=${WATCHTOWER_LABEL_ENABLE:-false}
      # https://containrrr.dev/watchtower/arguments/#scheduling
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE:-0 0 0 * * *} ## https://pkg.go.dev/github.com/robfig/cron@v1.2.0#hdr-CRON_Expression_Format
      # Send notificatoin to Ntfy https://docs.ntfy.sh/examples/#watchtower-shoutrrr
      - WATCHTOWER_NOTIFICATION_SKIP_TITLE=True
      - WATCHTOWER_NOTIFICATION_URL=ntfy://:${NTFY_TOKEN:?Access token from ntfy server required}@${NTFY_FQDN:?Ntfy server domain name required}/${NTFY_TOPIC:?Ntfy subscription topic required}?title=${NTFY_TITLE:?Ntfy message topic is needed}
    volumes:
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
