version: '3.6'

services:
  flame:
    image: pawelmalak/flame:${FLAME_VERSION:-latest}
    container_name: flame
    restart: unless-stopped
    user: root # Needed for docker integration
    volumes:
      - ${FLAME_PATH}:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "0.0.0.0:${FLAME_PORT:-5005}:5005"
    environment:
      - PASSWORD=${FLAME_PASSWORD}
    # healthcheck:
    #   test: "curl --fail https://localhost:${FLAME_PORT:-5005}:5005 || exit 1"
    #   interval: 60s
    #   retries: 5
    #   start_period: 60s
    #   timeout: 10s