# Cloudflare tunnel network container

# To get access in other containers use
# networks:
#   cloudflare:
#    external: true
networks:
  default:
    name: cloudflare
    driver: bridge

services:
  cloudflared:
    # https://github.com/cloudflare/cloudflared/releases
    image: cloudflare/cloudflared:${CLOUDFLARED_VERSION:-latest}
    container_name: cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"