version: "3"

networks:
  default: # this docker-compose network
    driver: bridge
  cloudflared_tunnel_network: # Cloudflare zero trust tunnel network
    external: true

services:
  portainer:
    # https://github.com/portainer/portainer
    image: portainer/portainer-ce:${PORTAINER_VERSION:-latest}
    container_name: portainer_app
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PORTAINER_PATH}:/data:Z
    networks:
      - default
      - cloudflared_tunnel_network
    ports:
      # - 8000:8000/tcp ## This second port is optional and only required if using Edge Compute features with Edge Agents
      - 9443:9443/tcp
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"