###############################################################################
# DOCKGE
# A fancy, easy-to-use and reactive self-hosted docker compose.yaml stack-oriented manager.
---
version: "3.8"

services:
  dockge:
    image: louislam/dockge:${DOCKGE_VERSION:-latest}
    container_name: dockge
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${STACKS_PATH:-/opt/docker_stacks}:/opt/stacks"
      - "${DOCKGE_PATH:-~/Docker/dockge/}/data:/app/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockge.service=dockge"
      - "traefik.http.routers.dockge.rule=Pathprefix(`/dockge`)"
      - "traefik.http.services.dockge.loadbalancer.server.port=5001"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    name: traefik_proxy
    external: true
