---
networks:
  default:
    name: semaphore
    driver: bridge
  cloudflare:
    external: true
  traefik:
    external: true

# Semaphore
# https://github.com/semaphoreui/semaphore/tree/develop?tab=readme-ov-file
services:
  postgres:
    image: postgres:${POSTGRESQL_VERSION:-latest}
    container_name: semaphore_postgres
    restart: unless-stopped
    networks:
      - default
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-semaphore}
      - POSTGRES_USER=${POSTGRES_USER:-semaphore}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-semaphore}
    volumes:
      - ${GF_PATH:-.}/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-semaphore} -d ${POSTGRES_DB:-semaphore}"]
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  
  # redis:
  #   image: docker.io/library/redis:alpine
  #   volumes:
  #     - redis:/data
  
  semaphore:
    container_name: semaphore_ui
    image: docker.io/semaphoreui/semaphore:${SEMAPHORE_VERSION:-latest}
    # user: "${UID}:${GID}"
    networks:
      - default
      - traefik
      - cloudflare
    ports:
      - 3003:3000
    environment:
      - SEMAPHORE_DB_DIALECT=postgres
      - SEMAPHORE_DB_HOST=postgres
      - SEMAPHORE_DB_PORT=5432
      - SEMAPHORE_DB_NAME=${POSTGRES_DB:-semaphore}
      - SEMAPHORE_DB_USER=${POSTGRES_USER:-semaphore}
      - SEMAPHORE_DB_PASS=${POSTGRES_PASSWORD:-semaphore}
      - SEMAPHORE_PLAYBOOK_PATH=${PLAYBOOK_PATH:-./ansible_playbooks}
      - SEMAPHORE_ADMIN_NAME=${SEMAPHORE_ADMIN_NAME:?Semaphore admin username required}
      - SEMAPHORE_ADMIN_PASSWORD=${SEMAPHORE_ADMIN_PASSWORD:?Semaphore admin password required}
      - SEMAPHORE_ADMIN_EMAIL=${SEMAPHORE_ADMIN_EMAIL:?Semaphore admin password required}
      - SEMAPHORE_ADMIN=${SEMAPHORE_ADMIN_NAME:?Semaphore admin username required}
      - SEMAPHORE_WEB_HOST=https://${SEMAPHORE_HOSTNAME}/${SEMAPHORE_URL_PATH}/
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=${SEMAPHORE_ACCESS_KEY_ENCRYPTION:?Semaphore uneque key required}
      - ANSIBLE_HOST_KEY_CHECKING=false  # (optional) change to true if you want to enable host key checking
    volumes:
      - ${SEMAPHORE_PATH:-.}/inventory/:/inventory:ro
      - ${SEMAPHORE_PATH:-.}/authorized_keys/:/authorized-keys:ro
      - ${SEMAPHORE_PATH:-.}/config/:/etc/semaphore:rw
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      ## Watch for container image updates
      - "com.centurylinklabs.watchtower.enable=true"

      ## Configure Treafik proxy
      ## https://blog.cubieserver.de/2020/configure-prometheus-on-a-sub-path-behind-reverse-proxy/
      - "traefik.enable=true"
      - "traefik.http.routers.semaphore.rule=Host(`${SEMAPHORE_HOSTNAME}`) && PathPrefix(`/${SEMAPHORE_URL_PATH}/`)"
      - "traefik.http.routers.semaphore.entrypoints=https"
      - "traefik.http.routers.semaphore.tls=true"
      - "traefik.http.services.semaphore.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik"